name: preparation

verified_data_dir: path/to/verified_truck_data
highway_labels_dir: path/to/highway_labels
weather_labels_dir: path/to/weather_labels

labeled_data_dir: path/to/labeled_data_dir
data_windows_dir: path/to/data_windows_dir
data_split_dir: path/to/truck_data_split
results_dir: path/to/label_distributions

file_extension: .parquet
window_extension: .npy

label_columns: 
  - air_temperature_label
  - surface_condition_label
  - weather_label
  - highway_label

signals_to_drop:
  weather_label:
    - airtempinsd_cval_hvac
    - airtempinsd_rq
    - airtempoutsd_cval_cpc
    - altitude_cval_ippc
    - latitude_cval_ippc
    - longitude_cval_ippc
  
  air_temperature_label:
    - airtempinsd_cval_hvac
    - airtempinsd_rq
    - airtempoutsd_cval_cpc
    - altitude_cval_ippc
    - latitude_cval_ippc
    - longitude_cval_ippc

  highway_label:
    - altitude_cval_ippc
    - latitude_cval_ippc
    - longitude_cval_ippc
    - vehspd_cval_cpc

labels_to_drop:
  highway_label:
    - living_street
    - motorway_link
    - primary_link
    - secondary_link
    - service
    - tertiary_link
    - track
    - trunk_link
    - unclassified
    - mini_roundabout
 
window_sizes_sec:
  - 100
  - 500

training_pct: 0.7      
validation_pct: 0.15    
test_pct: 0.15
fewshot_pct: 0.1          
    


